-- Add new AuditStatus enum values
ALTER TYPE "AuditStatus" ADD VALUE IF NOT EXISTS 'SELECTING_COMPETITORS';
ALTER TYPE "AuditStatus" ADD VALUE IF NOT EXISTS 'SELECTING_TOPICS';

-- Add new columns to Audit table
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "targetKeywords" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "pipelineState" JSONB;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "isNewSite" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "crawlComplete" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "suggestedCompetitors" JSONB;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "selectedCompetitors" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "suggestedClusters" JSONB;
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "selectedClusters" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Audit" ADD COLUMN IF NOT EXISTS "prefetchedRankings" JSONB;

-- Add coreWebVitals to CrawledPage
ALTER TABLE "CrawledPage" ADD COLUMN IF NOT EXISTS "coreWebVitals" JSONB;
